(function(){try{var k=true,l=null,n=false;window.gbar.tev&&window.gbar.tev(3,"gl");var o=window.gbar;var p={a:1,j:2,g:3,d:4,c:5,f:6,e:7,b:8};var q=this,r=function(a,b,c){a=a.split(".");c=c||q;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)if(!a.length&&b!==undefined)c[e]=b;else c=c[e]?c[e]:c[e]={}};var t=[],u=l,w=function(a,b){var c=l;if(b)c={m:b};o.tev&&o.tev(a,"gl",c)};window.gapi=window.gapi||{};
var x=/^(https?:)?\/\/([^\/:@]*)(:[0-9]+)?(\/[\w.,:!=\/-]*)(\?[^#]*)?(#.*)?$/,y=/^[?#]([^&]*&)*jsh=([^&]*)/,z=function(a){var b=window.console;b&&b.warn("gapi.load: "+a)},A=function(a,b,c){a=a.h;if(b=b&&y.exec(b)||c&&y.exec(c))try{a=decodeURIComponent(b[2])}catch(e){z("Invalid hint "+b[2])}return a},B=function(a){a.sort();for(var b=0;b<a.length;)if(!a[b]||b&&a[b]==a[b-1])a.splice(b,1);else++b},C=function(a,b){for(var c=k,e=0,d=0,f,g;c&&(f=a[e])&&(g=b[d]);){if(f==g)++e;else if(f<g)c=n;++d}return c&&
!f},D=function(a){if(document.readyState!="loading")return n;if(typeof window.___gapisync!="undefined")return window.___gapisync;if(a){a=a.sync;if(typeof a!="undefined")return a}a=document.getElementsByTagName("meta");for(var b=0,c;c=a[b];++b)if("generator"==c.getAttribute("name")&&"blogger"==c.getAttribute("content"))return k;return n},E=function(a,b){if(D(a))document.write('<script src="'+encodeURI(b)+'"><\/script>');else{var c=document.createElement("script");c.setAttribute("src",b);c.async=k;
var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(c,e)}},F=function(a,b,c,e,d,f){var g=c.shift(),h;if(g=="r")h="https://ssl.gstatic.com";else if(g=="m")h=e.ms||"https://apis.google.com";else h=(h=c.shift())&&h.replace(/\/+$/,"");var i;if(g=="r"){i=c.shift();i=(i.indexOf("/webclient/jsx/")?"/webclient/js/":"")+i}else i=c.shift();var j=g=="d",m=j&&c.shift()||"gcjs-3p";c=j&&c.shift();if(g=="d"){d="/"+a.join(":")+(b.length?"!"+b.join(":"):"")+".js?container="+m+"&c=2&jsload=0";
if(i)d+="&r="+i;if(c=="d")d+="&debug=1"}else if(g=="r"||g=="f")d=(i.indexOf("/")?"/":"")+i+"/"+a.join("__")+(b.length?"--"+b.join("__"):"")+".js";else if(g=="m"||g=="n"){a=a.join(",").replace(/\./g,"_").replace(/-/g,"_");a=i.replace("__features__",a);a=d.nodep?a.replace("/d=1/","/d=0/"):a;if(f){a.match(/\/$/)||(a+="/");a+="cb=gapi."+encodeURIComponent(f)}d=a}else{z("Unknown hint type "+g);return""}if(!h)return"";d=h+d;if(h=f=x.exec(d))if(h=!/\.\.|\/\//.test(f[4]))a:{f=f[2];if(g=="r")h=d.substr(0,
23)=="https://ssl.gstatic.com";else if(g=="m"){e=e.ms||"https://apis.google.com";h=d.substr(0,e.length)==e}else{e=e.m;if(f&&e){e=e.split(",");g=0;for(h=e.length;g<h;++g){a=e[g];b=f.lastIndexOf(a);if((b==0||a.charAt(0)=="."||f.charAt(b-1)==".")&&f.length-a.length==b){h=k;break a}}}h=n}}if(!h)throw"gapi.load: Invalid URI"+(d&&" "+d);return d},G=function(a,b,c){if(c)(a[b]=a[b]||[]).push(c)},I=function(a){if(a.q&&a.q.length>0)(window.gapi.load||H).apply(l,a.q.shift())},J=function(a){if(a)try{a()}catch(b){return b}return l},
K=window.gapi,L=function(){if(K._)return K._;var a;if((a=Object.create)&&/\[native code\]/.test(a))a=a(l);else{a={};for(var b in a)a[b]=void 0}return K._=a},N=function(a,b,c,e,d){var f=d.Q=d.Q||[],g=d.lc=d.lc||{};f.push([a,b,e]);K[c]=function(h){K[c]=undefined;if(!g[a]){g[a]=h;for(var i;f[0]&&g[f[0][0]];){h=f.shift();M(h[2],d);g[h[0]].call(window,L());g[h[0]]=k;if((h=J(h[1]))&&!i)i=h}d.p=void 0;I(d);if(i)throw i;}}},M=function(a,b){G(b,"ci",a._ci);var c=a.config;K.config?K.config.update(c):G(b,"cu",
c)},O=function(a){a.I||(a.I=0);return"loaded"+a.I++},H=function(a,b){var c,e={};if(typeof b!=="function"){e=b||{};c=e.callback}else c=b;var d=window.___jsl=window.___jsl||{},f=A(d,window.location.search,window.location.hash),g=f&&!!f.match(/\/gapi\/|ms=gapi/);if(d.p)G(d,"q",[a,b]);else{if(!f)throw"gapi.load: No hint present";var h=f.split(";"),i=h[0]=="m"||h[0]=="n";f=[];var j=[];if(d.il&&typeof d.il==="function"){f=d.il(a);e.nodep=1}else{f=a.split(":");e.nodep||B(f);j=d.l=d.l||[];B(j)}if(g){if(!C(f,
j)){g=O(d);if(h=F(f,j,h,d,e,g)){d.p=f;N(h,c,g,e,d);j.push.apply(j,f);E(e,h);return}}M(e,d);if(c)var m=J(c)}else{M(e,d);if(!C(f,j)){var s=i?"cm":"c";if(h=F(f,j,h,d,e,l)){d.p=f;d.o=1;d[s]=function(){d.p=void 0;d[s]=void 0;var v=J(c);I(d);if(v)throw v;};j.push.apply(j,f);E(e,h);return}}m=J(c)}I(d);if(m)throw m;}};t.push(["gl",{init:function(a){r("gbar.dgl",H,void 0);a["export"]&&r("gapi.load",H,void 0)}}]);w(p.b);
(function(){w(p.d);var a,b;for(a=0;b=o.bnc[a];++a)if(b[0]=="gl")break;if(b&&!b[1].l){a=function(){for(var c=o.mdc,e=o.mdi||{},d=0,f;f=t[d];++d){var g=f[0],h=c[g],i=e[g],j;if(j=h){if(i=!i){var m;a:{i=g;if(j=o.mdd)try{if(!u){u={};var s=j.split(/;/);for(j=0;j<s.length;++j)u[s[j]]=k}m=u[i];break a}catch(v){o.logger&&o.logger.ml(v)}m=n}i=!m}j=i}if(j){w(p.f,g);try{f[1].init(h);e[g]=k}catch(P){o.logger&&o.logger.ml(P)}w(p.e,g)}}if(c=o.qd.gl){o.qd.gl=[];for(e=0;d=c[e];++e)try{d()}catch(Q){o.logger&&o.logger.ml(Q)}}b[1].l=
k;w(p.c);a:{for(c=0;e=o.bnc[c];++c)if((e[1].auto||e[0]=="m")&&!e[1].l){c=n;break a}c=k}c&&w(p.a)};if(!b[1].libs||o.agl&&o.agl(b[1].libs))a();else b[1].i=a}})();}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"gl.init"});}})();
